### PR TITLE
Additional packages, cleanup and keywording

### PR DESCRIPTION
**Pull request by r7l**
As said earlier, i wanted to redo the PR. I've also asked you in our internal discussions about moving the Ebuilds to our overlay directly. But since you've not responded yet, i thought it might be better to do a PR here first.

I've set all the keywording to unstable and removed a bunch of architectures, we might not be able to support. Not sure if you want to keep them. I am only running ARM and Intel/AMD based systems. I am not able to test anything else.

Some of the Ebuilds are more or less copies of those still in Portage. Just with the support for older PHP versions. I wasn't sure about PHP 5.x and for that reason those `dev-php` packages are not having support for it yet.

I am still in favor for adding them those Ebuild to the PHP overlay.

### CODE REVIEW

**Comment by r7l** [comment]
Any thoughts about the PR? To much?

**Comment by fcool** [comment]
All fine for me. The only thing, which I'm not yet completely settled is the move to testing for those, which had already been marked stable.

We probably need to find some definition for stable - or we might even decide, that they are all at least keyword masked...

Apart from that: Great addition!

**Comment by r7l** [comment]
Some people might want to use the PHP Overlay mainly for Composer. By setting them to unstable / testing, those packages won't be pulled in by accident. People will have to unlock them one by one. 

The way we provide these packages, they are pretty much *unstable* already by using them with an outdated and unmaintained version of PHP. People using stable versions of PHP, probably won't need those packages in the first place. They are better of with the ones from Gentoo. At least they should be.

**Comment by fcool** [comment]
Agreed!

**Pull request merged**
